# Recipe created by recipetool
# This is the basis of a recipe and may need further editing in order to be fully functional.
# (Feel free to remove these comments when editing.)

SUMMARY = "Node.js package to access serial ports. Linux, OSX and Windows. Welcome your robotic JavaScript overlords. Better yet, program them!"
# WARNING: the following LICENSE and LIC_FILES_CHKSUM values are best guesses - it is
# your responsibility to verify that the values are complete and correct.
#
# The following license files were not able to be identified and are
# represented as "Unknown" below, you will need to check them yourself:
#   node_modules/prebuild-install/node_modules/rc/LICENSE.APACHE2
#   node_modules/prebuild-install/node_modules/rc/LICENSE.BSD
#   node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/bl/LICENSE.md
#   node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/bl/node_modules/readable-stream/LICENSE
#   node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream/LICENSE
#   node_modules/prebuild-install/node_modules/detect-libc/LICENSE
#   node_modules/prebuild-install/node_modules/tunnel-agent/LICENSE
#   node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/LICENSE
#   node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/string_decoder/LICENSE
#   node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/process-nextick-args/license.md
#   node_modules/nan/LICENSE.md
#
# NOTE: multiple licenses have been detected; they have been separated with &
# in the LICENSE value for now since it is a reasonable assumption that all
# of the licenses apply. If instead there is a choice between the multiple
# licenses then you should change the value to separate the licenses with |
# instead of &. If there is any doubt, check the accompanying documentation
# to determine which situation is applicable.
LICENSE = "Unknown & MIT & Apache-2.0 & WTFPL & ISC"
LIC_FILES_CHKSUM = "file://LICENSE;md5=e2bc0aa64d278eb2b6ddeb692e294945 \
                    file://node_modules/prebuild-install/LICENSE;md5=a75272c6b584d0f8e2c1676b4e72469e \
                    file://node_modules/prebuild-install/node_modules/rc/LICENSE.MIT;md5=e0f70a42adf526e6f5e605a94d98a420 \
                    file://node_modules/prebuild-install/node_modules/rc/LICENSE.APACHE2;md5=ffcf739dca268cb0f20336d6c1a038f1 \
                    file://node_modules/prebuild-install/node_modules/rc/LICENSE.BSD;md5=e7a2a325a0069e82aff675bbf74464a0 \
                    file://node_modules/prebuild-install/node_modules/rc/node_modules/deep-extend/LICENSE;md5=827bb5781213ff1e9d2fe309bbfc0115 \
                    file://node_modules/prebuild-install/node_modules/rc/node_modules/minimist/LICENSE;md5=aea1cde69645f4b99be4ff7ca9abcce1 \
                    file://node_modules/prebuild-install/node_modules/rc/node_modules/ini/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/prebuild-install/node_modules/rc/node_modules/strip-json-comments/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prebuild-install/node_modules/tar-fs/LICENSE;md5=9befe7026bf915886cd566a98117c80e \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/chownr/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/mkdirp/LICENSE;md5=b2d989bc186e7f6b418a5fdd5cc0b56b \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/LICENSE;md5=9befe7026bf915886cd566a98117c80e \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/bl/LICENSE.md;md5=e58dc7a94bb9decf6a7b2ff97d22b213 \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/bl/node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/bl/node_modules/readable-stream/LICENSE;md5=a67a7926e54316d90c14f74f71080977 \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/fs-constants/LICENSE;md5=0033175ba371b569c73d23fd726c37e8 \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/xtend/LICENCE;md5=96bcdf84e670aafacac9e094bce29ac9 \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/end-of-stream/LICENSE;md5=9befe7026bf915886cd566a98117c80e \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream/LICENSE;md5=a67a7926e54316d90c14f74f71080977 \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/to-buffer/LICENSE;md5=42014010547e55bd3bcac2fec8c45624 \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/pump/LICENSE;md5=9befe7026bf915886cd566a98117c80e \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/pump/node_modules/once/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/prebuild-install/node_modules/tar-fs/node_modules/pump/node_modules/end-of-stream/LICENSE;md5=9befe7026bf915886cd566a98117c80e \
                    file://node_modules/prebuild-install/node_modules/node-abi/LICENSE;md5=950ded031080d1cc5efffec127b7a852 \
                    file://node_modules/prebuild-install/node_modules/node-abi/node_modules/semver/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/prebuild-install/node_modules/detect-libc/LICENSE;md5=e3fc50a88d0a364313df4b21ef20c29e \
                    file://node_modules/prebuild-install/node_modules/os-homedir/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prebuild-install/node_modules/minimist/LICENSE;md5=aea1cde69645f4b99be4ff7ca9abcce1 \
                    file://node_modules/prebuild-install/node_modules/mkdirp/LICENSE;md5=b2d989bc186e7f6b418a5fdd5cc0b56b \
                    file://node_modules/prebuild-install/node_modules/mkdirp/node_modules/minimist/LICENSE;md5=aea1cde69645f4b99be4ff7ca9abcce1 \
                    file://node_modules/prebuild-install/node_modules/simple-get/LICENSE;md5=fb42e5aa12bb9e365d38b4b5691d6984 \
                    file://node_modules/prebuild-install/node_modules/simple-get/node_modules/simple-concat/LICENSE;md5=fb42e5aa12bb9e365d38b4b5691d6984 \
                    file://node_modules/prebuild-install/node_modules/simple-get/node_modules/decompress-response/license;md5=5b422d6bf88afe88977d04f8bdd4959c \
                    file://node_modules/prebuild-install/node_modules/simple-get/node_modules/decompress-response/node_modules/mimic-response/license;md5=915042b5df33c31a6db2b37eadaa00e3 \
                    file://node_modules/prebuild-install/node_modules/simple-get/node_modules/once/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/prebuild-install/node_modules/tunnel-agent/LICENSE;md5=f3f8ead5440d1c311b45be065d135d90 \
                    file://node_modules/prebuild-install/node_modules/tunnel-agent/node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/prebuild-install/node_modules/which-pm-runs/LICENSE;md5=a2661af2f2ec8fb665254e547ed4ac87 \
                    file://node_modules/prebuild-install/node_modules/github-from-package/LICENSE;md5=aea1cde69645f4b99be4ff7ca9abcce1 \
                    file://node_modules/prebuild-install/node_modules/pump/LICENSE;md5=9befe7026bf915886cd566a98117c80e \
                    file://node_modules/prebuild-install/node_modules/pump/node_modules/once/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/prebuild-install/node_modules/pump/node_modules/once/node_modules/wrappy/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/prebuild-install/node_modules/pump/node_modules/end-of-stream/LICENSE;md5=9befe7026bf915886cd566a98117c80e \
                    file://node_modules/prebuild-install/node_modules/pump/node_modules/end-of-stream/node_modules/once/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/prebuild-install/node_modules/npmlog/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/console-control-strings/LICENSE;md5=43abbc6f9093aea69560715033788727 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/LICENSE;md5=43abbc6f9093aea69560715033788727 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/strip-ansi/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/object-assign/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/has-unicode/LICENSE;md5=2bab5b1c26e9c44fc4e489bb98cfb196 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/wide-align/LICENSE;md5=9d215c9223fbef14a4642cc450e7ed4b \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/wide-align/node_modules/string-width/license;md5=915042b5df33c31a6db2b37eadaa00e3 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/console-control-strings/LICENSE;md5=43abbc6f9093aea69560715033788727 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/string-width/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/string-width/node_modules/strip-ansi/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/string-width/node_modules/strip-ansi/node_modules/ansi-regex/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/string-width/node_modules/code-point-at/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/string-width/node_modules/is-fullwidth-code-point/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/string-width/node_modules/is-fullwidth-code-point/node_modules/number-is-nan/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/LICENSE.txt;md5=e29e20260a1c78dba16a233048565cde \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/gauge/node_modules/aproba/LICENSE;md5=9d215c9223fbef14a4642cc450e7ed4b \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/LICENSE;md5=039a23da29f56411e6d75d7b7bc9de13 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/LICENSE;md5=a67a7926e54316d90c14f74f71080977 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/inherits/LICENSE;md5=5b2ef2247af6d355ae9d9f988092d470 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/string_decoder/LICENSE;md5=14af51f8c0a6c6e400b53e18c6e5f85c \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/string_decoder/node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/core-util-is/LICENSE;md5=6126e36127d20ec0e2f637204a5c68ff \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/process-nextick-args/license.md;md5=216769dac98a78ec088ee7cc6fad1dfa \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/util-deprecate/LICENSE;md5=b7c99ef4b0f3ad9911a52219947f8cf0 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/delegates/License;md5=039225978c07bc42e8c0ef2f72b81c09 \
                    file://node_modules/prebuild-install/node_modules/npmlog/node_modules/set-blocking/LICENSE.txt;md5=8fd106383180f7bbb8f534414fdf7d35 \
                    file://node_modules/debug/LICENSE;md5=ddd815a475e7338b0be7a14d8ee35a99 \
                    file://node_modules/commander/LICENSE;md5=25851d4d10d6611a12d5571dab945a00 \
                    file://node_modules/@serialport/parser-ready/node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/@serialport/parser-delimiter/node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/@serialport/parser-byte-length/node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/@serialport/parser-regex/node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/@serialport/parser-cctalk/node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/@serialport/parser-readline/node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/nan/LICENSE.md;md5=e6270b7774528599f2623a4aeb625829 \
                    file://node_modules/prompt-list/LICENSE;md5=62927f9e287cbc1dbddd9c8f208b7cdb \
                    file://node_modules/prompt-list/node_modules/ansi-cyan/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/ansi-cyan/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/ansi-dim/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/ansi-dim/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/LICENSE;md5=446d1cf3de4ea6a42746be233a220a1b \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/LICENSE;md5=446d1cf3de4ea6a42746be233a220a1b \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/ansi-cyan/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/LICENSE;md5=446d1cf3de4ea6a42746be233a220a1b \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/LICENSE;md5=d4f36f2681729e3ad311515c316b42ff \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/define-property/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/define-property/node_modules/is-descriptor/LICENSE;md5=78c705080a639d3bb4085a9d1bb22987 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/define-property/node_modules/is-descriptor/node_modules/kind-of/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/define-property/node_modules/is-descriptor/node_modules/is-accessor-descriptor/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/define-property/node_modules/is-descriptor/node_modules/is-accessor-descriptor/node_modules/kind-of/LICENSE;md5=c8f80ed52c9074414e8a69541cdc1587 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/define-property/node_modules/is-descriptor/node_modules/is-data-descriptor/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/define-property/node_modules/is-descriptor/node_modules/is-data-descriptor/node_modules/kind-of/LICENSE;md5=c8f80ed52c9074414e8a69541cdc1587 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/object-copy/LICENSE;md5=d4f36f2681729e3ad311515c316b42ff \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/object-copy/node_modules/kind-of/LICENSE;md5=c8f80ed52c9074414e8a69541cdc1587 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/object-copy/node_modules/define-property/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/static-extend/node_modules/object-copy/node_modules/copy-descriptor/LICENSE;md5=8a4b0e5fd41b2cf9072913a284384998 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-actions/LICENSE;md5=168f94bc7d2150e77c0dfd129126cd85 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-actions/node_modules/debug/LICENSE;md5=ddd815a475e7338b0be7a14d8ee35a99 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/component-emitter/LICENSE;md5=ee4aea2d350b7bdbf93e14297dcdd8a2 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/LICENSE;md5=446d1cf3de4ea6a42746be233a220a1b \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/kind-of/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/define-property/LICENSE;md5=7159ba8f2e9f17d4c29d1a73c4f4b759 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/define-property/node_modules/is-descriptor/LICENSE;md5=78c705080a639d3bb4085a9d1bb22987 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/define-property/node_modules/is-descriptor/node_modules/kind-of/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/define-property/node_modules/is-descriptor/node_modules/is-accessor-descriptor/LICENSE;md5=1027d1336ffdd3b96ff1cfd1d3bea3fc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/define-property/node_modules/is-descriptor/node_modules/is-accessor-descriptor/node_modules/kind-of/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/define-property/node_modules/is-descriptor/node_modules/is-data-descriptor/LICENSE;md5=1027d1336ffdd3b96ff1cfd1d3bea3fc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/define-property/node_modules/is-descriptor/node_modules/is-data-descriptor/node_modules/kind-of/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/debug/LICENSE;md5=ddd815a475e7338b0be7a14d8ee35a99 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/debug/node_modules/ms/license.md;md5=fd56fd5f1860961dfa92d313167c37a6 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/isobject/LICENSE;md5=2f5638b0557426da0c3bd67e00a0ebde \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/LICENSE;md5=2f5638b0557426da0c3bd67e00a0ebde \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/node_modules/kind-of/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/node_modules/is-plain-object/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/node_modules/shallow-clone/LICENSE;md5=78c705080a639d3bb4085a9d1bb22987 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/node_modules/shallow-clone/node_modules/kind-of/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/node_modules/shallow-clone/node_modules/mixin-object/LICENSE;md5=360e60c9b7aa16428ee600ff20935e1f \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/node_modules/shallow-clone/node_modules/mixin-object/node_modules/for-in/LICENSE;md5=c8f80ed52c9074414e8a69541cdc1587 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/node_modules/shallow-clone/node_modules/mixin-object/node_modules/is-extendable/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/node_modules/shallow-clone/node_modules/is-extendable/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/node_modules/for-own/LICENSE;md5=a9f606f2e3822130012aab1f9c6ed213 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/clone-deep/node_modules/for-own/node_modules/for-in/LICENSE;md5=c8f80ed52c9074414e8a69541cdc1587 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/koalas/LICENSE;md5=b436a81ca02af57e0e362bafa17f4571 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/LICENSE;md5=01a8b0026a66c0139b0434fba078fa92 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/choices-separator/LICENSE;md5=525d8ba712c1da523da9e6e7d61ff440 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/choices-separator/node_modules/debug/LICENSE;md5=ddd815a475e7338b0be7a14d8ee35a99 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/choices-separator/node_modules/ansi-dim/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/choices-separator/node_modules/strip-color/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/kind-of/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/arr-swap/LICENSE;md5=168f94bc7d2150e77c0dfd129126cd85 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/arr-swap/node_modules/is-number/LICENSE;md5=97b255bb4707da164bfaf4e5c7b9f9ef \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/arr-swap/node_modules/is-number/node_modules/kind-of/LICENSE;md5=c8f80ed52c9074414e8a69541cdc1587 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/define-property/LICENSE;md5=5fb5a7fdbcfa3640822ec69bd3ee86e7 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/define-property/node_modules/isobject/LICENSE;md5=2f5638b0557426da0c3bd67e00a0ebde \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/define-property/node_modules/is-descriptor/LICENSE;md5=78c705080a639d3bb4085a9d1bb22987 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/set-value/LICENSE;md5=ccdc0959f67943eb090f7e7c299621af \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/set-value/node_modules/is-plain-object/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/set-value/node_modules/is-plain-object/node_modules/isobject/LICENSE;md5=2f5638b0557426da0c3bd67e00a0ebde \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/radio-symbol/LICENSE;md5=525d8ba712c1da523da9e6e7d61ff440 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/radio-symbol/node_modules/ansi-gray/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/radio-symbol/node_modules/ansi-green/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/radio-symbol/node_modules/is-windows/LICENSE;md5=5fb5a7fdbcfa3640822ec69bd3ee86e7 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/pointer-symbol/LICENSE;md5=168f94bc7d2150e77c0dfd129126cd85 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/strip-color/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/clone-deep/LICENSE;md5=ccdc0959f67943eb090f7e7c299621af \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/clone-deep/node_modules/kind-of/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/clone-deep/node_modules/is-plain-object/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/clone-deep/node_modules/shallow-clone/LICENSE;md5=5fb5a7fdbcfa3640822ec69bd3ee86e7 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/clone-deep/node_modules/shallow-clone/node_modules/kind-of/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/collection-visit/LICENSE;md5=7159ba8f2e9f17d4c29d1a73c4f4b759 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/collection-visit/node_modules/map-visit/LICENSE;md5=f6db0829782d67e30695686ebb45970a \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/collection-visit/node_modules/map-visit/node_modules/object-visit/LICENSE;md5=7159ba8f2e9f17d4c29d1a73c4f4b759 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/collection-visit/node_modules/object-visit/LICENSE;md5=7159ba8f2e9f17d4c29d1a73c4f4b759 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/collection-visit/node_modules/object-visit/node_modules/isobject/LICENSE;md5=2f5638b0557426da0c3bd67e00a0ebde \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/koalas/LICENSE;md5=b436a81ca02af57e0e362bafa17f4571 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/arr-flatten/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/terminal-paginator/LICENSE;md5=525d8ba712c1da523da9e6e7d61ff440 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/terminal-paginator/node_modules/debug/LICENSE;md5=ddd815a475e7338b0be7a14d8ee35a99 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/terminal-paginator/node_modules/debug/node_modules/ms/license.md;md5=fd56fd5f1860961dfa92d313167c37a6 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/terminal-paginator/node_modules/extend-shallow/LICENSE;md5=360e60c9b7aa16428ee600ff20935e1f \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/terminal-paginator/node_modules/extend-shallow/node_modules/is-extendable/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/terminal-paginator/node_modules/log-utils/LICENSE;md5=d4f36f2681729e3ad311515c316b42ff \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/toggle-array/LICENSE;md5=525d8ba712c1da523da9e6e7d61ff440 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/toggle-array/node_modules/isobject/LICENSE;md5=2f5638b0557426da0c3bd67e00a0ebde \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/log-utils/LICENSE;md5=d4f36f2681729e3ad311515c316b42ff \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/prompt-question/node_modules/prompt-choices/node_modules/is-number/LICENSE;md5=ccdc0959f67943eb090f7e7c299621af \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/debug/LICENSE;md5=ddd815a475e7338b0be7a14d8ee35a99 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/koalas/LICENSE;md5=b436a81ca02af57e0e362bafa17f4571 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/LICENSE;md5=446d1cf3de4ea6a42746be233a220a1b \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/is-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/strip-color/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/koalas/LICENSE;md5=b436a81ca02af57e0e362bafa17f4571 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/arr-flatten/LICENSE;md5=3d83ea4c8ec9b31d9ff2c82fa29beabb \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/extend-shallow/LICENSE;md5=360e60c9b7aa16428ee600ff20935e1f \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/is-windows/LICENSE;md5=5fb5a7fdbcfa3640822ec69bd3ee86e7 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/mute-stream/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/is-number/LICENSE;md5=97b255bb4707da164bfaf4e5c7b9f9ef \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/window-size/LICENSE;md5=f6db0829782d67e30695686ebb45970a \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/window-size/node_modules/define-property/LICENSE;md5=7159ba8f2e9f17d4c29d1a73c4f4b759 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-utils/node_modules/window-size/node_modules/is-number/LICENSE;md5=97b255bb4707da164bfaf4e5c7b9f9ef \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/LICENSE;md5=d4f36f2681729e3ad311515c316b42ff \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/time-stamp/LICENSE;md5=f6db0829782d67e30695686ebb45970a \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/info-symbol/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/warning-symbol/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/log-ok/LICENSE;md5=d4f36f2681729e3ad311515c316b42ff \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/log-ok/node_modules/ansi-green/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/log-ok/node_modules/ansi-green/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/log-ok/node_modules/success-symbol/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/error-symbol/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/success-symbol/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/LICENSE;md5=c5465ad39efa0df062aecec7009a744b \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgmagenta/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgmagenta/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-hidden/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-hidden/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-gray/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-gray/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgred/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgred/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-blue/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-blue/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgwhite/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgwhite/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-green/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-cyan/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bold/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bold/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-italic/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-italic/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-reset/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-reset/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-grey/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-grey/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-yellow/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-yellow/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-dim/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgcyan/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgcyan/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-white/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-white/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgblue/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgblue/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-inverse/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-inverse/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-magenta/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-magenta/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgyellow/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgyellow/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-black/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-black/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bggreen/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bggreen/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-strikethrough/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-strikethrough/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/lazy-cache/LICENSE;md5=a0bd3ad96ad6f399ce73b75ce8332105 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/lazy-cache/node_modules/set-getter/LICENSE;md5=7874ce928b4b806b68bfe0db60986138 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/lazy-cache/node_modules/set-getter/node_modules/to-object-path/LICENSE;md5=a0bd3ad96ad6f399ce73b75ce8332105 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/lazy-cache/node_modules/set-getter/node_modules/to-object-path/node_modules/kind-of/LICENSE;md5=c8f80ed52c9074414e8a69541cdc1587 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/lazy-cache/node_modules/set-getter/node_modules/to-object-path/node_modules/kind-of/node_modules/is-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgblack/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-bgblack/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-red/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-red/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-underline/LICENSE;md5=12559a9acb747541ab67609d77c0f1de \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/log-utils/node_modules/ansi-colors/node_modules/ansi-underline/node_modules/ansi-wrap/LICENSE;md5=e060235353cb686ae1695ec7db63cfbc \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-ui/LICENSE;md5=525d8ba712c1da523da9e6e7d61ff440 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-ui/node_modules/component-emitter/LICENSE;md5=ee4aea2d350b7bdbf93e14297dcdd8a2 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-ui/node_modules/debug/LICENSE;md5=ddd815a475e7338b0be7a14d8ee35a99 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-ui/node_modules/string-width/license;md5=915042b5df33c31a6db2b37eadaa00e3 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-ui/node_modules/string-width/node_modules/strip-ansi/license;md5=915042b5df33c31a6db2b37eadaa00e3 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-ui/node_modules/string-width/node_modules/strip-ansi/node_modules/ansi-regex/license;md5=915042b5df33c31a6db2b37eadaa00e3 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-ui/node_modules/string-width/node_modules/is-fullwidth-code-point/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/prompt-base/node_modules/readline-ui/node_modules/readline-utils/LICENSE;md5=446d1cf3de4ea6a42746be233a220a1b \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/prompt-checkbox/node_modules/debug/LICENSE;md5=ddd815a475e7338b0be7a14d8ee35a99 \
                    file://node_modules/prompt-list/node_modules/prompt-radio/node_modules/debug/LICENSE;md5=ddd815a475e7338b0be7a14d8ee35a99 \
                    file://node_modules/safe-buffer/LICENSE;md5=badd5e91c737e7ffdf10b40c1f907761 \
                    file://node_modules/promirepl/LICENSE;md5=7c9235e0e2b265ff151142bc57a3e9c0"

SRC_URI = "npm://registry.npmjs.org;name=serialport;version=${PV}"

NPM_SHRINKWRAP := "${THISDIR}/${PN}/npm-shrinkwrap.json"
NPM_LOCKDOWN := "${THISDIR}/${PN}/lockdown.json"

inherit npm

# Must be set after inherit npm since that itself sets S
S = "${WORKDIR}/npmpkg"
LICENSE_${PN}-bindings = "MIT"
LICENSE_${PN}-commander = "MIT"
LICENSE_${PN}-debug = "MIT"
LICENSE_${PN}-nan = "MIT"
LICENSE_${PN}-prebuild-install-detect-libc = "Apache-2.0"
LICENSE_${PN}-prebuild-install-expand-template = "WTFPL"
LICENSE_${PN}-prebuild-install-github-from-package = "MIT"
LICENSE_${PN}-prebuild-install-minimist = "MIT"
LICENSE_${PN}-prebuild-install-mkdirp-minimist = "MIT"
LICENSE_${PN}-prebuild-install-mkdirp = "MIT"
LICENSE_${PN}-prebuild-install-node-abi-semver = "ISC"
LICENSE_${PN}-prebuild-install-node-abi = "MIT"
LICENSE_${PN}-prebuild-install-noop-logger = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet-delegates = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet-readable-stream-core-util-is = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet-readable-stream-inherits = "ISC"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet-readable-stream-isarray = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet-readable-stream-process-nextick-args = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet-readable-stream-safe-buffer = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet-readable-stream-string-decoder-safe-buffer = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet-readable-stream-string-decoder = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet-readable-stream-util-deprecate = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet-readable-stream = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-are-we-there-yet = "ISC"
LICENSE_${PN}-prebuild-install-npmlog-console-control-strings = "ISC"
LICENSE_${PN}-prebuild-install-npmlog-gauge-aproba = "ISC"
LICENSE_${PN}-prebuild-install-npmlog-gauge-console-control-strings = "ISC"
LICENSE_${PN}-prebuild-install-npmlog-gauge-has-unicode = "ISC"
LICENSE_${PN}-prebuild-install-npmlog-gauge-object-assign = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-gauge-signal-exit = "ISC"
LICENSE_${PN}-prebuild-install-npmlog-gauge-string-width-code-point-at = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-gauge-string-width-is-fullwidth-code-point-number-is-nan = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-gauge-string-width-is-fullwidth-code-point = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-gauge-string-width-strip-ansi-ansi-regex = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-gauge-string-width-strip-ansi = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-gauge-string-width = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-gauge-strip-ansi = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-gauge-wide-align-string-width = "MIT"
LICENSE_${PN}-prebuild-install-npmlog-gauge-wide-align = "ISC"
LICENSE_${PN}-prebuild-install-npmlog-gauge = "ISC"
LICENSE_${PN}-prebuild-install-npmlog-set-blocking = "ISC"
LICENSE_${PN}-prebuild-install-npmlog = "ISC"
LICENSE_${PN}-prebuild-install-os-homedir = "MIT"
LICENSE_${PN}-prebuild-install-pump-end-of-stream-once = "ISC"
LICENSE_${PN}-prebuild-install-pump-end-of-stream = "MIT"
LICENSE_${PN}-prebuild-install-pump-once-wrappy = "ISC"
LICENSE_${PN}-prebuild-install-pump-once = "ISC"
LICENSE_${PN}-prebuild-install-pump = "MIT"
LICENSE_${PN}-prebuild-install-rc-deep-extend = "MIT"
LICENSE_${PN}-prebuild-install-rc-ini = "ISC"
LICENSE_${PN}-prebuild-install-rc-minimist = "MIT"
LICENSE_${PN}-prebuild-install-rc-strip-json-comments = "MIT"
LICENSE_${PN}-prebuild-install-rc = "Unknown MIT"
LICENSE_${PN}-prebuild-install-simple-get-decompress-response-mimic-response = "MIT"
LICENSE_${PN}-prebuild-install-simple-get-decompress-response = "MIT"
LICENSE_${PN}-prebuild-install-simple-get-once = "ISC"
LICENSE_${PN}-prebuild-install-simple-get-simple-concat = "MIT"
LICENSE_${PN}-prebuild-install-simple-get = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-chownr = "ISC"
LICENSE_${PN}-prebuild-install-tar-fs-mkdirp = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-pump-end-of-stream = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-pump-once = "ISC"
LICENSE_${PN}-prebuild-install-tar-fs-pump = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-bl-readable-stream = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-bl-safe-buffer = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-bl = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-buffer-alloc-buffer-alloc-unsafe = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-buffer-alloc-buffer-fill = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-buffer-alloc = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-end-of-stream = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-fs-constants = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-readable-stream = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-to-buffer = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream-xtend = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs-tar-stream = "MIT"
LICENSE_${PN}-prebuild-install-tar-fs = "MIT"
LICENSE_${PN}-prebuild-install-tunnel-agent-safe-buffer = "MIT"
LICENSE_${PN}-prebuild-install-tunnel-agent = "Apache-2.0"
LICENSE_${PN}-prebuild-install-which-pm-runs = "MIT"
LICENSE_${PN}-prebuild-install = "MIT"
LICENSE_${PN}-promirepl = "MIT"
LICENSE_${PN}-prompt-list-ansi-cyan-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-ansi-cyan = "MIT"
LICENSE_${PN}-prompt-list-ansi-dim-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-ansi-dim = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-debug = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-ansi-cyan = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-debug = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-component-emitter = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-debug = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-koalas = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgblack-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgblack = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgblue-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgblue = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgcyan-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgcyan = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bggreen-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bggreen = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgmagenta-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgmagenta = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgred-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgred = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgwhite-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgwhite = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgyellow-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bgyellow = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-black-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-black = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-blue-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-blue = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bold-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-bold = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-cyan = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-dim = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-gray-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-gray = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-green = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-grey-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-grey = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-hidden-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-hidden = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-inverse-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-inverse = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-italic-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-italic = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-magenta-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-magenta = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-red-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-red = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-reset-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-reset = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-strikethrough-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-strikethrough = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-underline-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-underline = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-white-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-white = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-yellow-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-ansi-yellow = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-lazy-cache-set-getter-to-object-path-kind-of-is-buffer = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-lazy-cache-set-getter-to-object-path-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-lazy-cache-set-getter-to-object-path = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-lazy-cache-set-getter = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors-lazy-cache = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-ansi-colors = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-error-symbol = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-info-symbol = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-log-ok-ansi-green-ansi-wrap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-log-ok-ansi-green = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-log-ok-success-symbol = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-log-ok = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-success-symbol = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-time-stamp = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils-warning-symbol = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-log-utils = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-actions-debug = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-actions = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep-for-own-for-in = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep-for-own = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep-is-plain-object = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep-shallow-clone-is-extendable = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep-shallow-clone-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep-shallow-clone-mixin-object-for-in = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep-shallow-clone-mixin-object-is-extendable = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep-shallow-clone-mixin-object = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep-shallow-clone = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-clone-deep = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-debug-ms = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-debug = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-define-property-is-descriptor-is-accessor-descriptor-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-define-property-is-descriptor-is-accessor-descriptor = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-define-property-is-descriptor-is-data-descriptor-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-define-property-is-descriptor-is-data-descriptor = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-define-property-is-descriptor-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-define-property-is-descriptor = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-define-property = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-isobject = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-koalas = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-arr-flatten = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-arr-swap-is-number-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-arr-swap-is-number = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-arr-swap = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-choices-separator-ansi-dim = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-choices-separator-debug = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-choices-separator-strip-color = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-choices-separator = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-clone-deep-is-plain-object = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-clone-deep-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-clone-deep-shallow-clone-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-clone-deep-shallow-clone = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-clone-deep = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-collection-visit-map-visit-object-visit = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-collection-visit-map-visit = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-collection-visit-object-visit-isobject = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-collection-visit-object-visit = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-collection-visit = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-define-property-is-descriptor = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-define-property-isobject = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-define-property = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-is-number = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-koalas = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-log-utils = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-pointer-symbol = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-radio-symbol-ansi-gray = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-radio-symbol-ansi-green = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-radio-symbol-is-windows = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-radio-symbol = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-set-value-is-plain-object-isobject = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-set-value-is-plain-object = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-set-value = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-strip-color = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-terminal-paginator-debug-ms = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-terminal-paginator-debug = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-terminal-paginator-extend-shallow-is-extendable = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-terminal-paginator-extend-shallow = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-terminal-paginator-log-utils = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-terminal-paginator = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-toggle-array-isobject = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices-toggle-array = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question-prompt-choices = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-prompt-question = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-ui-component-emitter = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-ui-debug = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-ui-readline-utils = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-ui-string-width-is-fullwidth-code-point = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-ui-string-width-strip-ansi-ansi-regex = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-ui-string-width-strip-ansi = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-ui-string-width = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-ui = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-arr-flatten = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-extend-shallow = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-is-buffer = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-is-number = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-is-windows = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-koalas = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-mute-stream = "ISC"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-strip-color = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-window-size-define-property = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-window-size-is-number = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils-window-size = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-readline-utils = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-define-property-is-descriptor-is-accessor-descriptor-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-define-property-is-descriptor-is-accessor-descriptor = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-define-property-is-descriptor-is-data-descriptor-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-define-property-is-descriptor-is-data-descriptor = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-define-property-is-descriptor-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-define-property-is-descriptor = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-define-property = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-object-copy-copy-descriptor = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-object-copy-define-property = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-object-copy-kind-of = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend-object-copy = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base-static-extend = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox-prompt-base = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio-prompt-checkbox = "MIT"
LICENSE_${PN}-prompt-list-prompt-radio = "MIT"
LICENSE_${PN}-prompt-list = "MIT"
LICENSE_${PN}-safe-buffer = "MIT"
LICENSE_${PN}-serialport-parser-byte-length-safe-buffer = "MIT"
LICENSE_${PN}-serialport-parser-cctalk-safe-buffer = "MIT"
LICENSE_${PN}-serialport-parser-delimiter-safe-buffer = "MIT"
LICENSE_${PN}-serialport-parser-readline-safe-buffer = "MIT"
LICENSE_${PN}-serialport-parser-ready-safe-buffer = "MIT"
LICENSE_${PN}-serialport-parser-regex-safe-buffer = "MIT"
LICENSE_${PN} = "MIT"

DEPENDS += " nodejs"
